common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common.views import account_views, profile_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', account_views.signup, name='signup'),
    path('delete_account/', account_views.delete_account, name='delete_account'),

    # 비밀번호 변경
    path('password_reset/', account_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', account_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    # 프로필
    path('profile/base/<int:user_id>/', profile_views.profile_base, name='profile_base'),
    path('profile/question/<int:user_id>/', profile_views.ProfileQuestionListView.as_view(), name='profile_question'),
    path('profile/answer/<int:user_id>/', profile_views.ProfileAnswerListView.as_view(), name='profile_answer'),
    path('profile/comment/<int:user_id>/', profile_views.ProfileCommentListView.as_view(), name='profile_comment'),
    path('profile/vote/<int:user_id>/', profile_views.ProfileVoteListView.as_view(), name='profile_vote'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from common.views import account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
    path('reset/<uidb64>/<token>/', account_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),  # 추가
    path('accounts/', include('allauth.urls')),  # allauth URL 추가
]

handler404 = 'common.views.common_views.page_not_found'

pybo/urls.py
from django.urls import path
from .views  import base_views, question_views, answer_views, comment_views, vote_views, recently_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('',
         base_views.redirect_to_question, name = 'redirect_to_question'),
    path('question/list/<str:category_name>', base_views.index, name='index'),
    path('question/detail/<int:question_id>/',
         base_views.detail, name = 'detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify,
         name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name = 'answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/',
         vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/',
         vote_views.vote_answer, name='vote_answer'),

    # recently_views.py
    path('recently/question/',
         recently_views.RecentlyQuestionListView.as_view(), name='recently_question'),
    path('recently/answer/',
         recently_views.RecentlyAnswerListView.as_view(), name='recently_answer'),
    path('recently/comment/',
         recently_views.RecentlyCommentListView.as_view(), name='recently_comment'),
]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=20, null=True, blank=True)
    has_answer = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pybo:index', args=[self.name])

class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='category_question')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_question')
    subject = models.CharField(max_length = 200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    hits = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject


    def update_hits(self):
        self.hits += 1
        self.save()

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True,
                                 on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import django.contrib.auth.forms as auth_forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

class PasswordResetForm(auth_forms.PasswordResetForm):
    username = auth_forms.UsernameField(label="사용자ID")  # CharField 대신 사용

    # validation 절차:
    # 1. username에 대응하는 User 인스턴스의 존재성 확인
    # 2. username에 대응하는 email과 입력받은 email이 동일한지 확인

    def clean_username(self):
        data = self.cleaned_data['username']
        if not User.objects.filter(username=data).exists():
            raise ValidationError("해당 사용자ID가 존재하지 않습니다.")

        return data

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")

        if username and email:
            if User.objects.get(username=username).email != email:
                raise ValidationError("사용자의 이메일 주소가 일치하지 않습니다")

    def get_users(self, email=''):
        active_users = User.objects.filter(**{
            'username__iexact': self.cleaned_data["username"],
            'is_active': True,
        })
        return (
            u for u in active_users
            if u.has_usable_password()
        )

common/views.py
from django.contrib.auth import authenticate, login, views as auth_views
from django.shortcuts import render, redirect
from common.forms import UserForm, PasswordResetForm
from django.urls import reverse_lazy

def signup(request):
    """
    회원가입
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form' : form})

class PasswordResetView(auth_views.PasswordResetView):
    """
    비밀번호 초기화 - 사용자ID, email 입력
    """
    template_name = 'common/password_reset.html'
    success_url = reverse_lazy('common:password_reset_done')
    form_class = PasswordResetForm
    # email_template_name = 'common/password_reset_email.html'


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    """
    비밀번호 초기화 - 메일 전송 완료
    """
    template_name = 'common/password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    """
    비밀번호 초기화 - 새로운 비밀번호 입력
    """
    template_name = 'common/password_reset_confirm.html'
    success_url = reverse_lazy('common:login')

common/views/account_views.py
from django.contrib.auth import authenticate, login, views as auth_views
from django.shortcuts import render, redirect
from common.forms import UserForm, PasswordResetForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from pybo.models import Question, Answer, Comment

def signup(request):
    """
    회원가입
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form' : form})



@login_required
def delete_account(request):
    """
    회원 탈퇴
    """
    user = request.user
    # 사용자 연관 데이터 삭제
    Question.objects.filter(author=user).delete()
    Answer.objects.filter(author=user).delete()
    Comment.objects.filter(author=user).delete()

    user.delete()
    return redirect('common:login')

class PasswordResetView(auth_views.PasswordResetView):
    """
    비밀번호 초기화 - 사용자ID, email 입력
    """
    template_name = 'common/password_reset.html'
    success_url = reverse_lazy('common:password_reset_done')
    form_class = PasswordResetForm
    # email_template_name = 'common/password_reset_email.html'


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    """
    비밀번호 초기화 - 메일 전송 완료
    """
    template_name = 'common/password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    """
    비밀번호 초기화 - 새로운 비밀번호 입력
    """
    template_name = 'common/password_reset_confirm.html'
    success_url = reverse_lazy('common:login')

common/views/common_views.py
from django.shortcuts import render

def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, 'common/404.html', {})

common/views/profile_views.py
from django.db.models import F, Count
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from itertools import chain
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from pybo.models import Question, Answer, Comment
from django.http import JsonResponse

import logging

logger = logging.getLogger(__name__)

def profile_base(request, user_id):
    """
    프로필 기본 정보
    """
    user = get_object_or_404(User, pk=user_id)
    context = {'profile_user':user, 'profile_type':'base'}
    return render(request, 'common/profile/profile_base.html', context)

class ProfileObjectListView(ListView):
    """
    프로필 목록 추상 클래스 뷰
    """
    paginate_by = 10  # 한 페이지에 표시할 개수

    def get_queryset(self) :
        self.profile_user = get_object_or_404(User, pk=self.kwargs['user_id'])
        self.so = self.request.GET.get('so', 'recent')
        object_list = self.model.objects.filter(author=self.profile_user)

        if self.so == 'recommend' :
            object_list = object_list.annotate(
                num_voter=Count('voter')).order_by('-num_voter', '-create_date')
        elif self.so == 'popular':
            object_list = object_list.annotate(
                num_answer=Count('answer')).order_by('-num_answer', '-create_date')
        elif self.so == 'hit':
            object_list = object_list.order_by('-hits', '-create_date')
        else :  # recent
            object_list = object_list.order_by('-create_date')

        return object_list

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', 1)
        paginator = Paginator(self.get_queryset(), self.paginate_by)

        try :
            object_list = paginator.page(page)
        except PageNotAnInteger :
            object_list = paginator.page(1)
        except EmptyPage :
            object_list = paginator.page(paginator.num_pages)

        context.update({
            'profile_user' : self.profile_user,
            'profile_type' : self.profile_type,
            'so' : self.so,
            'object_list' : object_list,
            'page_obj' : object_list,
            'is_paginated' : paginator.num_pages > 1,
        })
        return context

class ProfileQuestionListView(ProfileObjectListView):
    """
    작성한 질문 목록
    """
    model = Question
    template_name = 'common/profile/profile_question.html'
    profile_type = 'question'


class ProfileAnswerListView(ProfileObjectListView):
    """
    작성한 답변 목록
    """
    model = Answer
    template_name = 'common/profile/profile_answer.html'
    profile_type = 'answer'


class ProfileCommentListView(ProfileObjectListView):
    """
    작성한 댓글 목록
    """
    model = Comment
    template_name = 'common/profile/profile_comment.html'
    profile_type = 'comment'

class ProfileVoteListView(ProfileObjectListView):
    """작성한 댓글 목록"""
    template_name = 'common/profile/profile_vote.html'
    profile_type = 'vote'

    def get_queryset(self):
        self.profile_user = get_object_or_404(User, pk=self.kwargs['user_id'])
        question_list = self.profile_user.voter_question.all()
        answer_list = self.profile_user.voter_answer.annotate(category=F('question__category__description'))

        _queryset = sorted(
            chain(question_list, answer_list),
            key = lambda obj: obj.create_date,
            reverse=True
        )
        # 콘솔에 object_list 출력
        # logger.debug(f"ProfileVoteListView queryset: {_queryset}")
        # print(f"ProfileVoteListView queryset1111: {answer_list}")  # 터미널에서 바로 확인용
        return _queryset

    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, **kwargs)
        context.update({
            'profile_user' : self.profile_user,
            'profile_type' : self.profile_type,
        })

        # 콘솔에 object_list 출력
        # logger.debug(f"ProfileVoteListView queryset: {context}")
        # print(f"ProfileVoteListView queryset2222: {context}")  # 터미널에서 바로 확인용
        return context

templates/common/profile/profile_answer.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <h4 class="border-bottom pb-2 my-3">{{ profile_user.username }}</h4>
    {% include "common/profile/profile_tabs.html" %}

    <div class="row justify-content-between my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>
                    최신순
                </option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>
                    추천순
                </option>
            </select>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>게시판</th>
            <th>추천</th>
            <th style="width:50%">내용</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr class="text-center">
            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
            <td>{{ object.question.category.description }}</td>
            <td>
                {% if object.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 py-1">
                    {{ object.voter.all.count }}
                </span>
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{% url 'pybo:detail' object.question.id %}#answer_{{ object.id }}">
<!--                <a name="answer_{{ answer.id }}" >-->
                    {{ object.content|slice:":75" }}{% if object.content|length > 75 %}...{% endif %}
                </a>
            </td>
            <td>{{ object.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">답변이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 처음 페이지 -->
        {% if page_obj.number > 1 %}
        <li class="page-item">
            <a class="page-link" href="?page=1">
                처음
            </a>
        </li>
        {% endif %}
        <!-- 이전 페이지 -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link"
               data-page="{{ page_obj.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% if page_obj.paginator.num_pages > 1 %}
            {% if page_obj.number > 6 %}
            <li class="page-item disabled">
                <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
            {% for page_number in page_obj.paginator.page_range %}
            {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
                {% if page_number == page_obj.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}&so={{ so }}&kw={{ kw }}">

                        {{ page_number }}
                    </a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_number }}" href="#">
                        {{ page_number }}
                    </a>
                </li>
                {% endif %}
            {% endif %}
            {% endfor %}
            {% if page_obj.number < page_obj.paginator.num_pages|add:-5 %}
            <li class="page-item disabled">
                <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
        {% endif %}
        <!-- 다음 페이지 -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
               data-page="{{ page_obj.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
        <!-- 마지막 페이지 -->
        {% if page_obj.number < page_obj.paginator.num_pages %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                마지막
            </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->
</div>
<form id="searchForm" method="get" action="">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function(){
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $(".so").on('change', function(){
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/common/profile/profile_base.html
{% extends "base.html" %}

{% block content %}
<h4 class="border-bottom pb-2 my-3">{{ profile_user.username }}</h4>
{% include "common/profile/profile_tabs.html" %}

<div id="profile_base">
    {%if user == profile_user %}
        <div class="profile_title">이메일</div>
        <p class="mb-4">{{ profile_user.email }}</p>
        <form action="{% url 'common:delete_account' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">회원 탈퇴</button>
        </form>
    {% endif %}
</div>

{% endblock %}

templates/common/profile/profile_question.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <h4 class="border-bottom pb-2 my-3">{{ profile_user.username }}</h4>
    {% include "common/profile/profile_tabs.html" %}

    <div class="row justify-content-between my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>
                    최신순
                </option>
                <option value="hit" {% if so == 'hit' %}selected{% endif %}>
                    조회순
                </option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>
                    추천순
                </option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>
                    인기순
                </option>
            </select>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>게시판</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>조회수</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr class="text-center">
            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
            <td>{{ object.category.description }}</td>
            <td>
                {% if object.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 py-1">
                    {{ object.voter.all.count }}
                </span>
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{% url 'pybo:detail' object.id %}">
                    {{ object.subject }}
                    {% if object.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">
                        {{ object.answer_set.count }}
                    </span>
                    {% endif %}
                </a>
            </td>
            <td>{{ object.hits }}</td>
            <td>{{ object.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 처음 페이지 -->
        {% if page_obj.number > 1 %}
        <li class="page-item">
            <a class="page-link" href="?page=1">
                처음
            </a>
        </li>
        {% endif %}
        <!-- 이전 페이지 -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link"
               data-page="{{ page_obj.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% if page_obj.paginator.num_pages > 1 %}
            {% if page_obj.number > 6 %}
            <li class="page-item disabled">
                <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
            {% for page_number in page_obj.paginator.page_range %}
            {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
                {% if page_number == page_obj.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}&so={{ so }}&kw={{ kw }}">

                        {{ page_number }}
                    </a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_number }}" href="#">
                        {{ page_number }}
                    </a>
                </li>
                {% endif %}
            {% endif %}
            {% endfor %}
            {% if page_obj.number < page_obj.paginator.num_pages|add:-5 %}
            <li class="page-item disabled">
                <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
        {% endif %}
        <!-- 다음 페이지 -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
               data-page="{{ page_obj.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
        <!-- 마지막 페이지 -->
        {% if page_obj.number < page_obj.paginator.num_pages %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                마지막
            </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function(){
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $(".so").on('change', function(){
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/common/profile/profile_tabs.html
<ul class="nav nav-tabs">
    {% if not profile_user.id %}
    <li><strong>profile_user.id가 비어 있습니다!</strong></li>
    {% endif %}
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'base' %}active{% endif %}" href="{% url 'common:profile_base' profile_user.id %}">기본 정보</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'question' %}active{% endif %}" href="{% url 'common:profile_question' profile_user.id %}">질문</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'answer' %}active{% endif %}" href="{% url 'common:profile_answer' profile_user.id %}">답변</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'comment' %}active{% endif %}" href="{% url 'common:profile_comment' profile_user.id %}">댓글</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if profile_type == 'vote' %}active{% endif %}" href="{% url 'common:profile_vote' profile_user.id %}">추천</a>
    </li>
</ul>